<?php

namespace App\Repository;

/**
 * NginxErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NginxErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
