<?php

namespace App\Repository;

/**
 * NginxAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NginxAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
